.TH XERCES-C-SAMPLE 1 "22 Mar 2008"
.SH NAME
xerces-c \- xerces-c sample program
.SH DESCRIPTION
This program is part of the libxerces-c-samples package.  That package
supplies compiled versions of the sample programs that are included in
the libxerces-c-dev packages.  Please see the examples for details.
These programs are not intended for production use, but they may be
useful in helping to create bug reports that the xerces-c maintainers
can easily reproduce.
.SH SEE ALSO
.br
/usr/share/doc/libxerces-c-dev/examples
.br
/usr/share/doc/libxerces-c-doc/html
